### ISSUE TITLE
Infografía sistemas numéricos By López Dominguez

### ISSUE THREAD

**Issue by 23620031** [SistemasTecTlaxiaco/infografia-23620031#2]
[López Domínguez Isaías Brayan.docx](https://github.com/SistemasTecTlaxiaco/infografia-23620031/files/12500999/Lopez.Dominguez.Isaias.Brayan.docx)
[López Domínguez Isaías Brayan.pdf](https://github.com/SistemasTecTlaxiaco/infografia-23620031/files/12501000/Lopez.Dominguez.Isaias.Brayan.pdf)

**Comment by Felix-Angel** [comment]
Redacción y ortografía: 10%
Exposición de ideas centrales 13% (No cuenta con 10 ideas principales)
Organización de  la información: 15%
Uso de imágenes y colores: 15%
Presentación visual: 15%
Referencias: 15%
Presentación: 15%
Calificación: 19.6/20
Calificado por equipo "Mayra, Daniel, Diego, Félix"

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
